-- ─────────────────────────────────────────────────────────────
-- MoodScript normalized schema
-- Embeddings and emotion score maps are stored as JSON text for
-- portability (works with or without the pgvector extension).
-- ─────────────────────────────────────────────────────────────

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE journal_entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title      VARCHAR(200) NOT NULL,
    body       TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_entries_user_created ON journal_entries(user_id, created_at DESC);

CREATE TABLE sentiment_scores (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id        BIGINT NOT NULL UNIQUE REFERENCES journal_entries(id) ON DELETE CASCADE,
    label           VARCHAR(20)  NOT NULL,           -- positive | negative | neutral
    pos             DOUBLE PRECISION NOT NULL DEFAULT 0,
    neg             DOUBLE PRECISION NOT NULL DEFAULT 0,
    neu             DOUBLE PRECISION NOT NULL DEFAULT 0,
    compound        DOUBLE PRECISION NOT NULL DEFAULT 0, -- -1..1
    primary_emotion VARCHAR(30),                     -- joy, sadness, anger, fear...
    emotion_scores  TEXT,                            -- JSON: {"joy":0.8,...}
    model_name      VARCHAR(120),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE mood_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    entry_id   BIGINT REFERENCES journal_entries(id) ON DELETE CASCADE,
    mood_label VARCHAR(30) NOT NULL,
    mood_score DOUBLE PRECISION NOT NULL,            -- 0..1 valence
    source     VARCHAR(10) NOT NULL DEFAULT 'auto',  -- auto | manual
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_moods_user_created ON mood_logs(user_id, created_at);

CREATE TABLE entry_embeddings (
    entry_id   BIGINT PRIMARY KEY REFERENCES journal_entries(id) ON DELETE CASCADE,
    embedding  TEXT NOT NULL,          -- JSON float array
    model_name VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE chat_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title      VARCHAR(200) NOT NULL DEFAULT 'New conversation',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_sessions_user ON chat_sessions(user_id, created_at DESC);

CREATE TABLE chat_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role       VARCHAR(12) NOT NULL,   -- user | assistant
    content    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_messages_session ON chat_messages(session_id, created_at);
